from __future__ import annotations

from mcp.server import Server

from resources.register_resources import register_resources
from tools.register_tools import register_tools
from version import SERVER_NAME, SERVER_VERSION


def create_mcp_server() -> Server:
    server = Server(
        SERVER_NAME,
        version=SERVER_VERSION,
        instructions="\n".join(
            [
                f"# Unity-AI-Forge MCP Server v{SERVER_VERSION} - Quick Reference",
                "AI駆動型Unity開発ツールキット。MCPサーバー + GameKitフレームワーク。3層構造（Low/Mid/High-Level）で効率的な開発を実現。",
                "",
                "## 🔴 Critical Rules (必ず守る)",
                "1. .metaファイルは絶対に編集しない（Unity自動管理、手動編集は参照破壊）",
                "2. 全Unity操作にMCPツール（unity_*）を使用",
                "3. 変更前に operation='inspect' で対象を確認",
                "4. **ツール優先順位: High-Level → Mid-Level → Low-Level** の順で選択（下記参照）",
                "5. コンパイルが必要な操作は自動待機（ブリッジ再接続で解除）",
                "6. **UI優先設計**: 人間が操作・確認できるUIから優先的に実装する（下記参照）",
                "7. **シーン分割**: 機能ごとにシーンを分ける（下記参照）",
                "",
                "## 🎯 UI優先設計原則 (Human-First UI Design)",
                "",
                "ゲーム開発では、人間が操作・デバッグできるUIを最初に作成することで、開発効率と品質が大幅に向上します。",
                "",
                "### なぜUI優先か？",
                "1. **即座のフィードバック**: UIがあればゲームの状態を視覚的に確認できる",
                "2. **手動テスト**: AIが作成したロジックを人間が手動でテスト可能",
                "3. **デバッグ容易**: 問題発生時にUIからゲーム状態を確認・操作できる",
                "4. **イテレーション高速化**: パラメータ調整をUI経由でリアルタイムに行える",
                "",
                "### 推奨実装順序:",
                "```",
                "1. Canvas/UI構造 → unity_ui_foundation",
                "2. デバッグUI（ステータス表示、ログ表示）",
                "3. 操作UI（ボタン、スライダー）→ unity_gamekit_ui_command",
                "4. ゲームロジック → unity_gamekit_actor, unity_gamekit_manager",
                "5. インタラクション → unity_gamekit_interaction",
                "```",
                "",
                "### UI優先の実装例:",
                "```python",
                "# ❌ 悪い例: ロジックを先に作り、UIは後回し",
                "# 1. プレイヤーアクター作成",
                "# 2. 敵AI作成",
                "# 3. 戦闘ロジック実装",
                "# 4. UI作成（最後）",
                "",
                "# ✅ 良い例: UIを先に作り、ロジックは後",
                "# 1. Canvas作成",
                "unity_ui_foundation(operation='createCanvas', name='GameUI')",
                "",
                "# 2. ステータス表示UI",
                "unity_ui_foundation(operation='createText', parentPath='GameUI', name='HPText', text='HP: 100/100')",
                "unity_ui_foundation(operation='createText', parentPath='GameUI', name='MPText', text='MP: 50/50')",
                "",
                "# 3. 操作ボタンUI（GameKitUICommand）",
                "unity_gamekit_ui_command(",
                "    operation='createCommandPanel',",
                "    panelId='ActionPanel',",
                "    canvasPath='GameUI',",
                "    commands=[",
                "        {'name': 'Attack', 'commandType': 'action', 'label': '攻撃'},",
                "        {'name': 'Heal', 'commandType': 'action', 'label': '回復'},",
                "    ],",
                "    targetType='actor',",
                "    targetActorId='player'",
                ")",
                "",
                "# 4. その後でゲームロジック実装",
                "unity_gamekit_actor(operation='create', actorId='player', ...)",
                "```",
                "",
                "### デバッグUI推奨パターン:",
                "- **リソース表示**: HP/MP/Gold等の現在値をテキストで表示",
                "- **ステート表示**: 現在のゲームフェーズ/ターンを表示",
                "- **操作ボタン**: 手動でターン進行、リソース追加/消費をテスト",
                "- **ログパネル**: イベント発生時のログ表示",
                "",
                "## 🎬 シーン分割原則 (Scene Separation)",
                "",
                "Unityプロジェクトでは、機能ごとにシーンを分割することで保守性と再利用性が向上します。",
                "",
                "### なぜシーン分割か？",
                "1. **並行開発**: 複数人が同時に異なるシーンで作業可能",
                "2. **メモリ効率**: 必要なシーンのみロードしてメモリ節約",
                "3. **テスト容易**: 個別シーンを単独でテスト可能",
                "4. **再利用性**: UI/Audio/Managerシーンを複数レベルで共有",
                "5. **ビルド最適化**: 不要なシーンを除外してビルドサイズ削減",
                "",
                "### 推奨シーン構成:",
                "```",
                "Assets/Scenes/",
                "├── Boot.unity           # 初期化、マネージャー生成",
                "├── Title.unity          # タイトル画面",
                "├── MainMenu.unity       # メインメニュー",
                "├── Loading.unity        # ローディング画面（Additive）",
                "├── GameUI.unity         # ゲームUI（Additive、複数レベルで共有）",
                "├── AudioManager.unity   # オーディオ管理（Additive、DontDestroyOnLoad）",
                "├── Levels/",
                "│   ├── Level1.unity     # ゲームプレイシーン",
                "│   ├── Level2.unity",
                "│   └── ...",
                "└── Debug/",
                "    └── TestScene.unity  # デバッグ用",
                "```",
                "",
                "### シーン分割の実装例:",
                "```python",
                "# 1. ブートシーンでマネージャー初期化",
                "unity_scene_crud(operation='create', scenePath='Assets/Scenes/Boot.unity')",
                "",
                "# 2. GameKitSceneFlowでシーン遷移を定義",
                "unity_gamekit_sceneflow(",
                "    operation='create',",
                "    flowId='MainFlow',",
                ")",
                "unity_gamekit_sceneflow(",
                "    operation='addScene',",
                "    flowId='MainFlow',",
                "    sceneName='Title',",
                "    scenePath='Assets/Scenes/Title.unity',",
                "    loadMode='single'",
                ")",
                "unity_gamekit_sceneflow(",
                "    operation='addScene',",
                "    flowId='MainFlow',",
                "    sceneName='Level1',",
                "    scenePath='Assets/Scenes/Levels/Level1.unity',",
                "    loadMode='single',",
                "    sharedScenePaths=['Assets/Scenes/GameUI.unity', 'Assets/Scenes/AudioManager.unity']",
                ")",
                "",
                "# 3. シーン間遷移を定義",
                "unity_gamekit_sceneflow(",
                "    operation='addTransition',",
                "    flowId='MainFlow',",
                "    fromScene='Title',",
                "    toScene='Level1',",
                "    trigger='StartGame'",
                ")",
                "```",
                "",
                "### シーンタイプ別ガイド:",
                "| シーンタイプ | loadMode | 用途 |",
                "|------------|----------|------|",
                "| Boot | single | 起動時初期化、GameManagerなど |",
                "| Menu/Title | single | 画面単位の切り替え |",
                "| Level | single | ゲームプレイ本体 |",
                "| UI Overlay | additive | 複数レベルで共有するUI |",
                "| Audio | additive | BGM/SE管理（DontDestroyOnLoad） |",
                "| Debug | single | テスト・デバッグ用 |",
                "",
                "## 🏗️ 3層アーキテクチャ",
                "",
                "### Low-Level CRUD (8ツール) - 基本操作",
                "Scene, GameObject, Component, Asset, ScriptableObject, Prefab, VectorSprite, ProjectSettings",
                "用途: 詳細な制御、単一オブジェクト操作、プロパティ精密設定",
                "",
                "### Mid-Level Batch (14ツール) - バッチ操作とプリセット",
                "Transform, RectTransform, Physics, Camera, UI Foundation, Audio, Input, CharacterController, Tilemap, Sprite2D, Animation2D, UI Hierarchy, UI State, UI Navigation",
                "用途: 複数オブジェクト一括処理、プリセット適用、レイアウト調整、2Dスプライト/アニメーション管理、宣言的UI構築",
                "",
                "### High-Level GameKit (14ツール) - ゲームシステム構築",
                "Actor, Manager, Interaction, UICommand, Machinations, SceneFlow, Health, Spawner, Timer, AI, Collectible, Projectile, Waypoint, TriggerZone",
                "用途: ゲームメカニクス、ターン制御、リソース経済、シーン遷移、インタラクション、HP/ダメージ、スポーン、タイマー/クールダウン、AI行動、収集アイテム、弾丸/ミサイル、パス追従、トリガーゾーン",
                "",
                "## 基本ワークフロー",
                "1. 確認: unity_scene_crud(operation='inspect', includeHierarchy=True)",
                "2. 操作: 適切なレイヤーのツールで変更実施",
                "3. 検証: operation='inspect' で結果確認",
                "",
                "## 🔄 バッチ順次処理 (推奨: 複雑な多段階操作)",
                "",
                "### unity_batch_sequential_execute - 順次実行＆リジューム機能",
                "複数のUnity操作を順番に実行し、エラー時に停止して再開できるツール。",
                "",
                "**主な機能:**",
                "- 順次実行: 操作を1つずつ順番に実行",
                "- エラー停止: 最初のエラーで停止し、残りの操作を保存",
                "- リジューム: 失敗した操作から再開可能",
                "- 進捗管理: 実行状態の保存と確認",
                "",
                "**使用例:**",
                "```python",
                "# 新規実行: 複数のGameObjectを順番に作成",
                "unity_batch_sequential_execute(",
                "    operations=[",
                "        {'tool': 'unity_gameobject_crud', 'arguments': {'operation': 'create', 'name': 'Enemy1', 'parentPath': 'Enemies'}},",
                "        {'tool': 'unity_component_crud', 'arguments': {'operation': 'add', 'gameObjectPath': 'Enemies/Enemy1', 'componentType': 'UnityEngine.Rigidbody2D'}},",
                "        {'tool': 'unity_gameobject_crud', 'arguments': {'operation': 'create', 'name': 'Enemy2', 'parentPath': 'Enemies'}},",
                "        {'tool': 'unity_component_crud', 'arguments': {'operation': 'add', 'gameObjectPath': 'Enemies/Enemy2', 'componentType': 'UnityEngine.Rigidbody2D'}},",
                "    ],",
                "    resume=False,",
                "    stop_on_error=True",
                ")",
                "",
                "# リジューム: エラーから再開",
                "unity_batch_sequential_execute(resume=True)",
                "```",
                "",
                "**ユースケース:**",
                "- シーンセットアップ: 複数のGameObject作成とコンポーネント追加",
                "- レベル構築: 地形、敵、アイテムの段階的配置",
                "- 設定変更: 複数のプロジェクト設定を順番に更新",
                "- 依存関係: 前の操作の成功が必要な一連の操作",
                "",
                "**リソース確認:**",
                "バッチキューの状態は unity_batch_queue_status リソースで確認可能",
                "",
                "## 🎮 High-Level GameKit Tools (推奨: ゲームシステム構築)",
                "",
                "### GameKit Actor - ゲームアクター",
                "- 作成: unity_gamekit_actor(operation='create', actorId='player_001', actorType='player', behaviorProfile='2dPhysics'|'2dLinear'|'2dTileGrid'|'3dCharacterController'|'3dPhysics'|'3dNavMesh', controlMode='directController'|'aiAutonomous'|'uiCommand'|'scriptTriggerOnly', stats={'health': 100, 'speed': 5.0}, abilities=['Jump', 'Attack'])",
                "- 更新: unity_gamekit_actor(operation='update', actorId='...', stats={'health': 80})",
                "- 検査: unity_gamekit_actor(operation='inspect', actorId='...')",
                "",
                "### GameKit Manager - ゲームマネージャー",
                "- 作成: unity_gamekit_manager(operation='create', managerId='game_manager', managerType='turnBased'|'realtime'|'resourcePool'|'eventHub'|'stateManager', turnPhases=['PlayerTurn', 'EnemyTurn'], resourcePool={'actionPoints': 3}, dontDestroyOnLoad=True)",
                "- ターン進行: unity_gamekit_manager(operation='update', managerId='...', advancePhase=True)",
                "- リソース消費: unity_gamekit_manager(operation='update', managerId='...', consumeResource={'resourceName': 'actionPoints', 'amount': 1})",
                "",
                "### GameKit Interaction - インタラクション",
                "- 作成: unity_gamekit_interaction(operation='create', interactionId='door_trigger', triggerType='trigger'|'collision'|'raycast'|'proximity'|'input', actions=[{'type': 'changeScene', 'target': 'Level2'}], conditions=[{'type': 'tag', 'value': 'Player'}])",
                "- アクションタイプ: spawnPrefab, destroyObject, playSound, sendMessage, changeScene",
                "",
                "### GameKit UI Command - UIコマンドパネル",
                "- 作成: unity_gamekit_ui_command(operation='createCommandPanel', panelName='CommandPanel', commands=['Move', 'Attack', 'Defend'], layout='horizontal'|'vertical'|'grid', targetActorId='player_001')",
                "",
                "### GameKit Machinations - リソース経済システム",
                "Machinations風のリソースフロー管理。再利用可能なScriptableObjectアセットとして定義。",
                "",
                "**4つの構成要素:**",
                "1. Resource Pools: リソースプール（HP、MP、Gold等）の初期値/最小値/最大値",
                "2. Resource Flows: 時間経過による自動生成/消費（例: 毎秒MP+1回復）",
                "3. Resource Converters: リソース変換（例: Gold 10 → HP 50）",
                "4. Resource Triggers: 閾値イベント（例: HP≤0で死亡イベント）",
                "",
                "**操作:**",
                "- アセット作成: unity_gamekit_machinations(operation='create', diagramId='player_economy', assetPath='Assets/Economy/PlayerEconomy.asset', initialResources=[{'name': 'health', 'initialAmount': 100, 'minValue': 0, 'maxValue': 100}, {'name': 'mana', 'initialAmount': 50, 'minValue': 0, 'maxValue': 100}], flows=[{'flowId': 'manaRegen', 'resourceName': 'mana', 'ratePerSecond': 1.0, 'isSource': True, 'enabledByDefault': True}], converters=[{'converterId': 'healthPotion', 'fromResource': 'gold', 'toResource': 'health', 'conversionRate': 5.0, 'inputCost': 10}], triggers=[{'triggerName': 'death', 'resourceName': 'health', 'thresholdType': 'below', 'thresholdValue': 1, 'enabledByDefault': True}])",
                "- アセット更新: unity_gamekit_machinations(operation='update', assetPath='...', flows=[...])",
                "- アセット検査: unity_gamekit_machinations(operation='inspect', assetPath='...')",
                "- マネージャーに適用: unity_gamekit_machinations(operation='apply', assetPath='...', managerId='resource_manager', resetExisting=False)",
                "- マネージャーから出力: unity_gamekit_machinations(operation='export', managerId='...', assetPath='Assets/Exported.asset')",
                "- アセット削除: unity_gamekit_machinations(operation='delete', assetPath='...')",
                "",
                "**ユースケース:**",
                "- RPGの体力/魔力システム（自動回復、ポーション変換）",
                "- リソース管理ゲーム（木材→建物、食料消費）",
                "- カードゲーム（コスト消費、ターン毎のエネルギー回復）",
                "- 経済シミュレーション（生産/消費/貿易フロー）",
                "",
                "### GameKit SceneFlow - シーン遷移管理",
                "- 作成: unity_gamekit_sceneflow(operation='create', flowId='main_flow', scenes=[{'name': 'Title', 'path': 'Assets/Scenes/Title.unity', 'loadMode': 'single'}, {'name': 'Level1', 'path': '...', 'loadMode': 'additive', 'sharedGroups': ['UI', 'Audio']}], sharedSceneGroups={'UI': ['Assets/Scenes/GameUI.unity']}, transitions=[{'from': 'Title', 'to': 'Level1', 'trigger': 'StartGame'}])",
                "- 遷移: unity_gamekit_sceneflow(operation='transition', flowId='...', trigger='StartGame')",
                "",
                "### GameKit Health - HP/ダメージシステム",
                "宣言的なHP/ダメージシステム。無敵時間、死亡時の動作、リスポーン対応。",
                "- 作成: unity_gamekit_health(operation='create', gameObjectPath='Player', healthId='player_hp', maxHealth=100, invincibilityDuration=1.0, deathBehavior='Respawn'|'Destroy'|'Disable'|'EventOnly', respawnDelay=2.0)",
                "- ダメージ: unity_gamekit_health(operation='applyDamage', healthId='player_hp', amount=25)",
                "- 回復: unity_gamekit_health(operation='heal', healthId='player_hp', amount=50)",
                "- 即死: unity_gamekit_health(operation='kill', healthId='player_hp')",
                "- リスポーン: unity_gamekit_health(operation='respawn', healthId='player_hp')",
                "- 無敵設定: unity_gamekit_health(operation='setInvincible', healthId='player_hp', enabled=True, duration=5.0)",
                "- UnityEvents: OnDamage, OnHeal, OnDeath, OnRespawn, OnInvincibilityStart/End",
                "",
                "### GameKit Spawner - スポーンシステム",
                "敵、アイテム、弾丸等のスポーン管理。ウェーブ制、オブジェクトプール対応。",
                "- 作成: unity_gamekit_spawner(operation='create', gameObjectPath='Spawner', spawnerId='enemy_spawner', prefabPath='Assets/Prefabs/Enemy.prefab', spawnMode='Interval'|'Wave'|'Burst'|'Manual', spawnInterval=3.0, maxSpawnCount=10, autoStart=True)",
                "- ウェーブ追加: unity_gamekit_spawner(operation='addWave', spawnerId='enemy_spawner', enemyCount=5, spawnInterval=1.0, delayAfterWave=5.0)",
                "- スポーン開始/停止: unity_gamekit_spawner(operation='start'|'stop', spawnerId='...')",
                "- 単体スポーン: unity_gamekit_spawner(operation='spawnOne', spawnerId='...')",
                "- バーストスポーン: unity_gamekit_spawner(operation='spawnBurst', spawnerId='...', count=10)",
                "- 全消去: unity_gamekit_spawner(operation='despawnAll', spawnerId='...')",
                "- UnityEvents: OnSpawn, OnDespawn, OnWaveStart/Complete, OnAllWavesComplete",
                "",
                "### GameKit Timer - タイマー/クールダウン",
                "タイマーとクールダウン管理。ループ、一時停止、ポーズ無視対応。",
                "- タイマー作成: unity_gamekit_timer(operation='createTimer', gameObjectPath='GameManager', timerId='round_timer', duration=60.0, loop=False, autoStart=True, useUnscaledTime=False)",
                "- タイマー操作: unity_gamekit_timer(operation='startTimer'|'stopTimer'|'pauseTimer'|'resumeTimer'|'resetTimer', timerId='...')",
                "- クールダウン作成: unity_gamekit_timer(operation='createCooldown', gameObjectPath='Player', cooldownId='attack_cd', duration=0.5)",
                "- クールダウン発動: unity_gamekit_timer(operation='triggerCooldown', cooldownId='attack_cd')",
                "- クールダウン検査: unity_gamekit_timer(operation='inspectCooldown', cooldownId='attack_cd') → isReady, remainingTime",
                "- UnityEvents: OnTimerStart, OnTimerComplete, OnTimerTick, OnCooldownReady",
                "",
                "### GameKit AI - AI行動",
                "パトロール、追跡、逃走等のAI行動。視野角、視線判定、状態機械対応。",
                "- 作成: unity_gamekit_ai(operation='create', gameObjectPath='Enemy', aiId='enemy_ai', behaviorType='Patrol'|'Chase'|'Flee'|'PatrolAndChase', moveSpeed=3.0, detectionRadius=8.0, fieldOfView=120, patrolMode='Loop'|'PingPong'|'Random')",
                "- パトロール地点追加: unity_gamekit_ai(operation='addPatrolPoint', aiId='enemy_ai', position={'x': 0, 'y': 0, 'z': 5})",
                "- ターゲット設定: unity_gamekit_ai(operation='setTarget', aiId='enemy_ai', targetPath='Player')",
                "- 状態変更: unity_gamekit_ai(operation='setState', aiId='enemy_ai', state='Idle'|'Patrol'|'Chase'|'Attack'|'Flee'|'Return')",
                "- UnityEvents: OnTargetDetected, OnTargetLost, OnStateChanged, OnPatrolPointReached, OnAttackRange",
                "",
                "### GameKit Collectible - 収集アイテム",
                "コイン、HP回復、パワーアップ、鍵等の収集アイテム。リスポーン、磁石効果対応。",
                "- 作成: unity_gamekit_collectible(operation='create', gameObjectPath='Coin', collectibleId='coin_001', collectibleType='Coin'|'Health'|'Ammo'|'Key'|'PowerUp'|'Experience'|'Custom', value=10, autoCollect=True, collectRadius=1.0)",
                "- 磁石効果: unity_gamekit_collectible(operation='update', collectibleId='coin_001', magnetEffect=True, magnetRadius=5.0, magnetSpeed=10.0)",
                "- リスポーン設定: unity_gamekit_collectible(operation='update', collectibleId='coin_001', respawnEnabled=True, respawnTime=30.0)",
                "- 収集: unity_gamekit_collectible(operation='collect', collectibleId='coin_001', collectorPath='Player')",
                "- リスポーン: unity_gamekit_collectible(operation='respawn', collectibleId='coin_001')",
                "- 全リセット: unity_gamekit_collectible(operation='reset', collectibleId='coin_001')",
                "- UnityEvents: OnCollected(collector, value), OnRespawn",
                "",
                "### GameKit Projectile - 弾丸/ミサイル",
                "弾丸、ミサイル、バウンドボール等の発射体。ホーミング、貫通、反射対応。",
                "- 作成: unity_gamekit_projectile(operation='create', gameObjectPath='Bullet', projectileId='bullet_001', movementType='Straight'|'Homing'|'Parabolic'|'Boomerang', speed=20.0, damage=10, lifetime=5.0)",
                "- ホーミング: unity_gamekit_projectile(operation='update', projectileId='bullet_001', movementType='Homing', homingStrength=5.0, maxTurnAngle=90)",
                "- 反射: unity_gamekit_projectile(operation='update', projectileId='bullet_001', bounceEnabled=True, maxBounces=3)",
                "- 貫通: unity_gamekit_projectile(operation='update', projectileId='bullet_001', piercing=True, maxPierceCount=5)",
                "- 発射: unity_gamekit_projectile(operation='launch', projectileId='bullet_001', direction={'x': 1, 'y': 0, 'z': 0})",
                "- ターゲット設定: unity_gamekit_projectile(operation='setHomingTarget', projectileId='bullet_001', targetPath='Enemy')",
                "- UnityEvents: OnLaunch, OnHit(target, damage), OnBounce, OnPierce, OnExpire",
                "",
                "### GameKit Waypoint - パス追従",
                "NPC、移動プラットフォーム等のパス追従。ループ、往復、停止時間対応。",
                "- 作成: unity_gamekit_waypoint(operation='create', gameObjectPath='Platform', waypointId='platform_001', pathMode='Once'|'Loop'|'PingPong', moveSpeed=3.0, autoStart=True)",
                "- ウェイポイント追加: unity_gamekit_waypoint(operation='addWaypoint', waypointId='platform_001', position={'x': 0, 'y': 5, 'z': 0}, waitTime=1.0)",
                "- ウェイポイント削除: unity_gamekit_waypoint(operation='removeWaypoint', waypointId='platform_001', index=0)",
                "- パス開始/停止: unity_gamekit_waypoint(operation='startPath'|'stopPath'|'pausePath'|'resumePath', waypointId='...')",
                "- 特定地点へ移動: unity_gamekit_waypoint(operation='goToWaypoint', waypointId='platform_001', index=2)",
                "- UnityEvents: OnWaypointReached(index), OnPathComplete, OnPathStart",
                "",
                "### GameKit TriggerZone - トリガーゾーン",
                "チェックポイント、ダメージゾーン、テレポーター等のトリガーゾーン。",
                "- 作成: unity_gamekit_trigger_zone(operation='create', gameObjectPath='Checkpoint', zoneId='checkpoint_001', zoneType='Checkpoint'|'DamageZone'|'HealZone'|'Teleport'|'SpeedBoost'|'SlowDown'|'KillZone'|'SafeZone'|'Trigger', is2D=True)",
                "- ダメージゾーン: unity_gamekit_trigger_zone(operation='update', zoneId='damage_zone', damagePerSecond=10.0, damageInterval=0.5)",
                "- テレポート設定: unity_gamekit_trigger_zone(operation='setTeleportDestination', zoneId='teleporter', destinationPath='SpawnPoint')",
                "- 速度変更ゾーン: unity_gamekit_trigger_zone(operation='update', zoneId='speed_zone', speedMultiplier=2.0, effectDuration=5.0)",
                "- 有効/無効: unity_gamekit_trigger_zone(operation='activate'|'deactivate', zoneId='...')",
                "- UnityEvents: OnZoneEnter(obj), OnZoneExit(obj), OnZoneStay(obj), OnTeleport, OnCheckpointActivated",
                "",
                "## ⚡ Mid-Level Batch Tools (推奨: バッチ操作)",
                "",
                "### Transform Batch - 配置とリネーム",
                "- 円形配置: unity_transform_batch(operation='arrangeCircle', gameObjectPaths=['Obj1', 'Obj2'], radius=5.0, startAngle=0)",
                "- 直線配置: unity_transform_batch(operation='arrangeLine', gameObjectPaths=[...], startPosition={...}, endPosition={...})",
                "- 連番リネーム: unity_transform_batch(operation='renameSequential', gameObjectPaths=[...], baseName='Enemy', startIndex=1, padding=3)",
                "",
                "### RectTransform Batch - UIレイアウト",
                "- アンカー設定: unity_rectTransform_batch(operation='setAnchors', gameObjectPaths=[...], anchorMin={'x': 0, 'y': 0}, anchorMax={'x': 1, 'y': 1})",
                "- 親に整列: unity_rectTransform_batch(operation='alignToParent', gameObjectPaths=[...], preset='topLeft'|'center'|'bottomRight')",
                "- 分配: unity_rectTransform_batch(operation='distribute', gameObjectPaths=[...], direction='horizontal'|'vertical', spacing=10)",
                "",
                "### Physics Bundle - 物理プリセット",
                "- 2Dプリセット: unity_physics_bundle(operation='applyPreset2D', gameObjectPath='...', preset='dynamic'|'kinematic'|'static'|'character'|'platformer'|'topDown'|'vehicle'|'projectile')",
                "- 3Dプリセット: unity_physics_bundle(operation='applyPreset3D', gameObjectPath='...', preset='dynamic'|'kinematic'|'static'|'character'|'vehicle'|'projectile')",
                "",
                "### Camera Rig - カメラ設定",
                "- 作成: unity_camera_rig(operation='createRig', rigType='follow'|'orbit'|'splitScreen'|'fixed'|'dolly', cameraName='MainCamera', targetPath='Player', offset={'x': 0, 'y': 5, 'z': -10}, smoothSpeed=5.0)",
                "",
                "### UI Foundation - UI基礎要素",
                "- Canvas: unity_ui_foundation(operation='createCanvas', name='GameUI', renderMode='screenSpaceOverlay'|'screenSpaceCamera'|'worldSpace')",
                "- Panel: unity_ui_foundation(operation='createPanel', name='Panel', parentPath='Canvas', anchorPreset='middleCenter', width=400, height=300)",
                "- Button: unity_ui_foundation(operation='createButton', name='Button', parentPath='Canvas', text='Click', anchorPreset='middleCenter', width=200, height=60)",
                "- LayoutGroup追加: unity_ui_foundation(operation='addLayoutGroup', targetPath='Canvas/Panel', layoutType='Vertical', spacing=10, padding={'left':10,'right':10,'top':10,'bottom':10})",
                "  ⚠️ layoutType: 'Horizontal'|'Vertical'|'Grid'  ※targetPath必須（parentPathではない）",
                "",
                "### UI Hierarchy - 宣言的UI構築",
                "JSON定義から複雑なUI階層を一括作成。メニュー、ダイアログ、HUDの高速構築に最適。",
                "- 作成: unity_ui_hierarchy(operation='create', parentPath='Canvas', hierarchy={'type': 'panel', 'name': 'Menu', 'children': [{'type': 'button', 'text': 'Start'}], 'layout': 'Vertical'})",
                "- クローン: unity_ui_hierarchy(operation='clone', gameObjectPath='Canvas/Menu', newName='MenuCopy')",
                "- 表示/非表示: unity_ui_hierarchy(operation='show'|'hide'|'toggle', gameObjectPath='Canvas/Menu')",
                "- ナビゲーション: unity_ui_hierarchy(operation='setNavigation', gameObjectPath='Canvas/Menu', navigationMode='auto-vertical')",
                "",
                "### UI State - UI状態管理",
                "UI要素の状態を定義・保存・適用。メニュー遷移、ダイアログ表示に便利。",
                "- 状態定義: unity_ui_state(operation='defineState', stateName='hidden', rootPath='Canvas/Dialog', elements=[{'path': '', 'active': False, 'alpha': 0}])",
                "- 状態適用: unity_ui_state(operation='applyState', stateName='hidden', rootPath='Canvas/Dialog')",
                "- 状態保存: unity_ui_state(operation='saveState', stateName='current', rootPath='Canvas/Dialog')",
                "- 状態グループ: unity_ui_state(operation='createStateGroup', groupName='MenuStates', states=['main', 'options', 'credits'])",
                "",
                "### UI Navigation - UIナビゲーション設定",
                "キーボード/ゲームパッド操作のナビゲーション設定。",
                "- 自動設定: unity_ui_navigation(operation='autoSetup', rootPath='Canvas/Menu', direction='vertical'|'horizontal'|'grid', wrapAround=True)",
                "- 明示的設定: unity_ui_navigation(operation='setExplicit', gameObjectPath='Canvas/Button1', up='Canvas/Button0', down='Canvas/Button2')",
                "- グループ作成: unity_ui_navigation(operation='createGroup', groupName='MenuButtons', elements=['Button1', 'Button2'], direction='vertical')",
                "",
                "### Audio Source Bundle - オーディオ設定",
                "- 作成: unity_audio_source_bundle(operation='createAudioSource', gameObjectPath='...', preset='music'|'sfx'|'ambient'|'voice'|'ui', audioClipPath='...', volume=1.0, loop=True)",
                "",
                "### Input Profile - 入力システム",
                "- 作成: unity_input_profile(operation='createPlayerInput', gameObjectPath='...', actionMapType='player'|'ui'|'vehicle', notificationBehavior='sendMessages'|'broadcastMessages'|'invokeUnityEvents')",
                "",
                "### Character Controller Bundle - 3Dキャラクター制御",
                "CharacterControllerコンポーネントを最適化されたプリセットで設定。3Dキャラクター移動に最適。",
                "",
                "**プリセット:**",
                "- fps: 1.8m高さ（一人称視点用）",
                "- tps: 2.0m高さ（三人称視点用）",
                "- platformer: 1.0m高さ（プラットフォーマー用）",
                "- child: 0.5m高さ（子供キャラクター用）",
                "- large: 3.0m高さ（大型キャラクター用）",
                "- narrow: 細いカプセル（狭い空間用）",
                "- custom: 完全手動設定",
                "",
                "**使用例:**",
                "- プリセット適用: unity_character_controller_bundle(operation='applyPreset', gameObjectPath='Player', preset='fps')",
                "- カスタム設定: unity_character_controller_bundle(operation='update', gameObjectPath='Player', radius=0.5, height=2.0, slopeLimit=45.0, stepOffset=0.3)",
                "- 検査: unity_character_controller_bundle(operation='inspect', gameObjectPath='Player')",
                "- バッチ適用: unity_character_controller_bundle(operation='applyPreset', gameObjectPaths=['Player1', 'Player2'], preset='tps')",
                "",
                "**自動設定されるパラメータ:**",
                "- radius: カプセル半径",
                "- height: カプセル高さ",
                "- center: カプセル中心オフセット",
                "- slopeLimit: 登れる坂の最大角度",
                "- stepOffset: 登れる段差の高さ",
                "- skinWidth: 衝突検出パディング",
                "- minMoveDistance: 移動判定閾値",
                "",
                "## 🔧 Low-Level CRUD Tools (詳細制御)",
                "",
                "### Scene & GameObject",
                "- 作成: unity_gameobject_crud(operation='create', name='...', parentPath='...')",
                "- 更新: unity_gameobject_crud(operation='update', gameObjectPath='...', tag='Player', layer='UI'|5, active=True, static=False)",
                "- レイヤー設定: unity_gameobject_crud(operation='update', gameObjectPath='Player', layer='UI') ※レイヤー名または番号",
                "- 複数検索: unity_gameobject_crud(operation='findMultiple', pattern='Enemy*', maxResults=100)",
                "- 移動: unity_gameobject_crud(operation='move', gameObjectPath='...', parentPath='...')",
                "",
                "### Component",
                "- 追加: unity_component_crud(operation='add', gameObjectPath='...', componentType='UnityEngine.Rigidbody', propertyChanges={...})",
                "- 更新: unity_component_crud(operation='update', gameObjectPath='...', componentType='...', propertyChanges={...})",
                "- バッチ追加: unity_component_crud(operation='addMultiple', pattern='Enemy*', componentType='...', stopOnError=False, maxResults=100)",
                "",
                "#### Unity Object参照 (propertyChanges内)",
                "- アセット参照: {'$ref': 'Assets/Materials/Player.mat'}",
                "- シーンオブジェクト: {'$ref': 'Canvas/Panel/Button'} ※非アクティブも検索可能",
                "- 文字列形式: 'Canvas/Panel' ※UnityEngine.Object型プロパティのみ",
                "",
                "### Asset & Script",
                "- テキストファイル作成: unity_asset_crud(operation='create', assetPath='Assets/Data/config.json', content='...')",
                "- 更新: unity_asset_crud(operation='update', assetPath='...', content='...')",
                "  ⚠️ C#スクリプト作成/更新後は自動コンパイル待機（60秒タイムアウト、ブリッジ再接続で解除）",
                "- インポーター設定: unity_asset_crud(operation='updateImporter', assetPath='...', propertyChanges={...})",
                "",
                "### ScriptableObject",
                "- 作成: unity_scriptableObject_crud(operation='create', typeName='MyGame.GameConfig', assetPath='Assets/Data/....asset', properties={...})",
                "- 検査: unity_scriptableObject_crud(operation='inspect', assetPath='...', includeProperties=True, propertyFilter=['version', 'maxPlayers'])",
                "- 更新: unity_scriptableObject_crud(operation='update', assetPath='...', properties={...})",
                "- 型検索: unity_scriptableObject_crud(operation='findByType', typeName='...', searchPath='Assets/Data', maxResults=100)",
                "",
                "### Prefab",
                "- 作成: unity_prefab_crud(operation='create', gameObjectPath='...', prefabPath='Assets/Prefabs/....prefab', includeChildren=True)",
                "- インスタンス化: unity_prefab_crud(operation='instantiate', prefabPath='...', targetPath='...', position={...}, rotation={...})",
                "- オーバーライド適用: unity_prefab_crud(operation='applyOverrides', gameObjectPath='...')",
                "- オーバーライド破棄: unity_prefab_crud(operation='revertOverrides', gameObjectPath='...')",
                "- アンパック: unity_prefab_crud(operation='unpack', gameObjectPath='...', unpackMode='outmostRoot'|'completely')",
                "",
                "### Vector Sprite (プロトタイプ用)",
                "外部アセット不要で即座に生成。ゲームジャム、プロトタイピング、プレースホルダーに最適。",
                "- プリミティブ: unity_vector_sprite_convert(operation='primitiveToSprite', primitiveType='circle'|'square'|'triangle'|'polygon', color={'r':1,'g':0,'b':0,'a':1}, outputPath='Assets/Sprites/....png', width=256, height=256)",
                "- 単色: unity_vector_sprite_convert(operation='createColorSprite', width=64, height=64, color={...}, outputPath='...')",
                "- SVG変換: unity_vector_sprite_convert(operation='svgToSprite', svgPath='...', outputPath='...', width=512, height=512)",
                "- テクスチャ→スプライト: unity_vector_sprite_convert(operation='textureToSprite', texturePath='...', pixelsPerUnit=100, filterMode='point'|'bilinear')",
                "",
                "### Project Settings",
                "- 読み取り: unity_projectSettings_crud(operation='read', category='player'|'quality'|'time'|'physics'|'physics2d'|'audio'|'editor'|'tagsLayers', property='...')",
                "- 書き込み: unity_projectSettings_crud(operation='write', category='...', property='...', value=...)",
                "- 2D重力設定: unity_projectSettings_crud(operation='write', category='physics2d', property='gravity', value={'x': 0, 'y': 0})",
                "- タグ追加: unity_projectSettings_crud(operation='write', category='tagsLayers', property='addTag', value='...')",
                "- レイヤー追加: unity_projectSettings_crud(operation='write', category='tagsLayers', property='addLayer', value='...')",
                "- ソートレイヤー追加/削除: unity_projectSettings_crud(operation='write', category='tagsLayers', property='addSortingLayer'|'removeSortingLayer', value='...')",
                "- レンダリングレイヤー追加/削除: unity_projectSettings_crud(operation='write', category='tagsLayers', property='addRenderingLayer'|'removeRenderingLayer', value='...')",
                "",
                "### Build Settings",
                "- ビルドシーン一覧: unity_projectSettings_crud(operation='listBuildScenes')",
                "- シーン追加: unity_projectSettings_crud(operation='addSceneToBuild', scenePath='Assets/Scenes/Level1.unity', index=0, enabled=True)",
                "- シーン削除: unity_projectSettings_crud(operation='removeSceneFromBuild', scenePath='...' または index=0)",
                "- シーン順序変更: unity_projectSettings_crud(operation='reorderBuildScenes', fromIndex=0, toIndex=2)",
                "- シーン有効/無効: unity_projectSettings_crud(operation='setBuildSceneEnabled', scenePath='...' または index=0, enabled=True)",
                "",
                "## ⚡ Performance & Best Practices",
                "",
                "### ツール選択ガイド:",
                "1. **ゲームシステム構築** → High-Level GameKit (Actor, Manager, Interaction, UICommand, Machinations, SceneFlow, Health, Spawner, Timer, AI, Collectible, Projectile, Waypoint, TriggerZone)",
                "2. **複数オブジェクト処理** → Mid-Level Batch (Transform, RectTransform, Physics, Camera, UI, Audio, Input, CharacterController)",
                "3. **詳細な個別制御** → Low-Level CRUD (GameObject, Component, Asset, ScriptableObject, Prefab)",
                "",
                "### 高速化テクニック:",
                "1. includeProperties=False: コンポーネント存在確認のみ（10倍高速）",
                "2. propertyFilter: 必要なプロパティのみ取得",
                "3. maxResults: 大量操作時のタイムアウト防止（デフォルト1000）",
                "4. stopOnError=False: バッチ処理でエラー時も続行",
                "",
                "### バッチ操作（推奨）:",
                "❌ 避ける: ループ内で個別ツール呼び出し",
                "✅ 推奨1: Mid-Level Batchツールまたは *Multiple 操作",
                "例: unity_transform_batch(operation='arrangeCircle', gameObjectPaths=[...])",
                "例: unity_component_crud(operation='addMultiple', pattern='Enemy*', ...)",
                "✅ 推奨2: 複雑な多段階処理には unity_batch_sequential_execute",
                "例: 複数のGameObject作成→コンポーネント追加→プロパティ設定の一連の流れ",
                "　　エラー時に停止し、修正後に resume=True で再開可能",
                "",
                "### コンパイル待機（自動）:",
                "- C#スクリプト作成/更新後、自動的にコンパイル待機",
                "- 待機中にブリッジが再接続されると即座に解除",
                "- タイムアウト: 60秒（設定変更不可）",
                "- レスポンスに compilationWait 情報が含まれる",
                "",
                "## 🎮 Game Development Workflow",
                "",
                "### 推奨開発フロー:",
                "1. **ゲームシステム設計** (High-Level GameKit)",
                "   - GameKit Actor: プレイヤー、敵、NPCの作成",
                "   - GameKit Manager: ターン制御、リソース管理",
                "   - GameKit Machinations: リソース経済システム（HP/MP回復、変換、閾値イベント）",
                "   - GameKit SceneFlow: シーン遷移設計",
                "",
                "2. **インタラクション実装** (High-Level GameKit)",
                "   - GameKit Interaction: トリガーとアクション定義",
                "   - GameKit UICommand: UIからのコマンド送信",
                "",
                "3. **詳細調整** (Mid/Low-Level)",
                "   - Mid-Level: 物理、カメラ、UI、オーディオのプリセット適用",
                "   - Low-Level: 個別プロパティの微調整",
                "",
                "4. **演出追加** (最後)",
                "   - パーティクル、アニメーション、サウンド",
                "   - UI遷移、フィードバック演出",
                "",
                "### GameKit使用例:",
                "```python",
                "# 1. プレイヤーアクター作成",
                "unity_gamekit_actor(operation='create', actorId='player', behaviorProfile='2dPhysics', controlMode='directController', stats={'health': 100})",
                "",
                "# 2. ターン制マネージャー作成",
                "unity_gamekit_manager(operation='create', managerId='turn_mgr', managerType='turnBased', turnPhases=['PlayerTurn', 'EnemyTurn'])",
                "",
                "# 3. リソース経済システム作成（Machinations）",
                "unity_gamekit_machinations(",
                "    operation='create',",
                "    diagramId='player_economy',",
                "    assetPath='Assets/Economy/PlayerEconomy.asset',",
                "    initialResources=[",
                "        {'name': 'health', 'initialAmount': 100, 'minValue': 0, 'maxValue': 100},",
                "        {'name': 'mana', 'initialAmount': 50, 'minValue': 0, 'maxValue': 100},",
                "        {'name': 'gold', 'initialAmount': 0, 'minValue': 0, 'maxValue': 9999}",
                "    ],",
                "    flows=[",
                "        {'flowId': 'manaRegen', 'resourceName': 'mana', 'ratePerSecond': 1.0, 'isSource': True}",
                "    ],",
                "    converters=[",
                "        {'converterId': 'healthPotion', 'fromResource': 'gold', 'toResource': 'health', 'conversionRate': 5.0, 'inputCost': 10}",
                "    ]",
                ")",
                "",
                "# 4. ドアトリガー作成",
                "unity_gamekit_interaction(operation='create', interactionId='door', triggerType='trigger', actions=[{'type': 'changeScene', 'target': 'Level2'}])",
                "",
                "# 5. シーンフロー設定",
                "unity_gamekit_sceneflow(operation='create', flowId='main', scenes=[...], transitions=[...])",
                "```",
                "",
                "### バッチ順次処理使用例（複雑なシーンセットアップ）:",
                "```python",
                "# 敵キャラクターを段階的にセットアップ（エラー時は停止してリジューム可能）",
                "unity_batch_sequential_execute(",
                "    operations=[",
                "        # ステップ1: 親オブジェクト作成",
                "        {'tool': 'unity_gameobject_crud', 'arguments': {'operation': 'create', 'name': 'Enemies'}},",
                "        # ステップ2-4: 敵キャラクター作成",
                "        {'tool': 'unity_gamekit_actor', 'arguments': {'operation': 'create', 'actorId': 'enemy1', 'parentPath': 'Enemies', 'behaviorProfile': '2dPhysics', 'controlMode': 'aiAutonomous'}},",
                "        {'tool': 'unity_gamekit_actor', 'arguments': {'operation': 'create', 'actorId': 'enemy2', 'parentPath': 'Enemies', 'behaviorProfile': '2dPhysics', 'controlMode': 'aiAutonomous'}},",
                "        {'tool': 'unity_gamekit_actor', 'arguments': {'operation': 'create', 'actorId': 'enemy3', 'parentPath': 'Enemies', 'behaviorProfile': '2dPhysics', 'controlMode': 'aiAutonomous'}},",
                "        # ステップ5: 敵を円形配置",
                "        {'tool': 'unity_transform_batch', 'arguments': {'operation': 'arrangeCircle', 'gameObjectPaths': ['Enemies/enemy1', 'Enemies/enemy2', 'Enemies/enemy3'], 'radius': 5.0}},",
                "    ]",
                ")",
                "```",
                "",
                "## 🔌 Utility Tools",
                "",
                "### unity_ping - 接続確認",
                "- 確認: unity_ping() でブリッジ接続状態を確認",
                "",
                "### unity_compilation_await - コンパイル待機",
                "C#スクリプト作成/更新後にコンパイル完了を待機。",
                "- 待機: unity_compilation_await(operation='await', timeoutSeconds=60)",
                "- 通常はスクリプト操作後に自動で呼び出されるが、明示的に待機したい場合に使用",
                "",
                "## 🔧 Troubleshooting",
                "",
                "### 接続エラー",
                "1. unity_ping で接続確認",
                "2. Unity Editor: Tools > MCP Assistant が起動しているか確認",
                "3. ポート7077が使用可能か確認",
                "",
                "### コンパイルエラー",
                "- C#スクリプト作成/更新後は自動コンパイル待機",
                "- レスポンスの compilationWait 情報を確認",
                "- Unity Editorのコンソールログでエラー詳細を確認",
                "",
                "### タイムアウト",
                "1. maxResults を減らす（デフォルト1000 → 100以下）",
                "2. includeProperties=False で高速化",
                "3. stopOnError=False でバッチ操作続行",
                "4. Mid-Level Batchツールを使用（個別呼び出しより高速）",
                "",
                "### ブリッジ再接続",
                "- コンパイル中にブリッジが再接続された場合、自動的に待機解除",
                "- レスポンスに bridgeReconnected: true が含まれる",
                "- 再接続後、操作を再試行してください",
                "",
                "### バッチ順次処理エラー",
                "- エラー発生時は stopped_at_index で失敗位置を確認",
                "- 問題を修正後、resume=True で再開",
                "- unity_batch_queue_status リソースで進捗確認",
                "- 完全にリセットする場合は新規実行（resume=False）",
                "",
                "## 📋 Quick Reference",
                "",
                "### 全38ツール一覧:",
                "",
                "**High-Level GameKit (14):**",
                "unity_gamekit_actor, unity_gamekit_manager, unity_gamekit_interaction, unity_gamekit_ui_command, unity_gamekit_machinations, unity_gamekit_sceneflow, unity_gamekit_health, unity_gamekit_spawner, unity_gamekit_timer, unity_gamekit_ai, unity_gamekit_collectible, unity_gamekit_projectile, unity_gamekit_waypoint, unity_gamekit_trigger_zone",
                "",
                "**Mid-Level Batch (14):**",
                "unity_transform_batch, unity_rectTransform_batch, unity_physics_bundle, unity_camera_rig, unity_ui_foundation, unity_ui_hierarchy, unity_ui_state, unity_ui_navigation, unity_audio_source_bundle, unity_input_profile, unity_character_controller_bundle, unity_tilemap_bundle, unity_sprite2d_bundle, unity_animation2d_bundle",
                "",
                "**Low-Level CRUD (8):**",
                "unity_scene_crud, unity_gameobject_crud, unity_component_crud, unity_asset_crud, unity_scriptableObject_crud, unity_prefab_crud, unity_vector_sprite_convert, unity_projectSettings_crud",
                "",
                "**Batch Operations (1):**",
                "unity_batch_sequential_execute",
                "",
                "**Utility (2):**",
                "unity_ping, unity_compilation_await",
                "",
                "### GameObject識別方法:",
                "- gameObjectPath: 階層パス（例: 'Canvas/Panel/Button'）",
                "- gameObjectGlobalObjectId: GlobalObjectId文字列（シーン再読み込み後も安定）",
                "",
                "### よくあるコンポーネントプロパティ:",
                "- Transform: position, rotation, localScale",
                "- RectTransform: anchoredPosition, sizeDelta, anchorMin, anchorMax, pivot",
                "- Rigidbody: mass, drag, useGravity, constraints",
                "- Rigidbody2D: mass, linearDamping, angularDamping, gravityScale, constraints",
                "- Camera: fieldOfView, clearFlags, backgroundColor",
                "",
                "### 命名規則:",
                "全ツール名は unity_* 形式（アンダースコア区切り）",
                "例: unity_gamekit_actor, unity_gamekit_machinations, unity_transform_batch, unity_character_controller_bundle, unity_gameobject_crud, unity_batch_sequential_execute",
                "",
                "---",
                f"Unity-AI-Forge v{SERVER_VERSION} - 38 Tools, 100+ Operations, 3-Layer Architecture + UI-First Design + Batch Processing + Machinations Economics + 2D Sprite/Animation + Physics2D + Sorting Layers + Declarative UI + GameKit Phase 1 & 2 (Health/Spawner/Timer/AI/Collectible/Projectile/Waypoint/TriggerZone)",
            ]
        ),
    )

    register_resources(server)
    register_tools(server)

    return server

