from __future__ import annotations

from mcp.server import Server

from resources.register_resources import register_resources
from tools.register_tools import register_tools
from version import SERVER_NAME, SERVER_VERSION


def create_mcp_server() -> Server:
    server = Server(
        SERVER_NAME,
        version=SERVER_VERSION,
        instructions="\n".join(
            [
                "Unityプロジェクトと連携する拡張版MCPサーバーです。",
                "resourcesからプロジェクト構造、シーン、ログ、アセットを参照し、toolsでUnityEditorを操作します。",
                "",
                "【ツール使用の原則】",
                "- UnityEditor操作は必ずMCPツール（unity.asset.crud、unity.gameobject.crud、unity.component.crud等）を使用する事",
                "- パラメータ取得やファイル読み書きも直接行わず、MCPツールを使用する事",
                "- ツール実行前に対象のオブジェクト/アセットのパスを確認する事",
                "- 接続タイムアウト時や切断時はコンパイルエラーを確認する事",
                "- **重要**: .metaファイルは絶対に編集しない（Unityが自動管理、手動編集は参照破壊の原因）",
                "",
                "【開発時の注意点】",
                "- 必要最小限の変更に留め、既存アセットを活用する事",
                "- ユーザーが明示的に要求した場合のみエディタ操作を実行する事",
                "- テンプレート機能を積極的に活用（手動作成の10倍高速）",
                "",
                "【開発作業の優先順位】",
                "1. C#スクリプトの作成（プロジェクトの基礎）",
                "2. GameObjectとコンポーネントの設定",
                "3. シーン構成とプレハブの作成",
                "",
                "【ゲームプロジェクト実装の推奨順序】",
                "ゲーム開発では以下の順序で実装することを強く推奨:",
                "1. UI実装",
                "   - まずゲームに必要なUIを全て作成・配置",
                "   - ボタン、テキスト、パネル、HUDなどの基本UI要素",
                "   - レイアウトとアンカー設定を完了させる",
                "   - この段階ではイベントハンドラは空のままでOK",
                "   理由: UIは後から追加すると位置調整やレイアウト崩れが発生しやすい",
                "",
                "2. ロジック実装",
                "   - ゲームの核となるロジック（ゲームルール、状態管理、スコア計算等）",
                "   - UIのイベントハンドラとロジックを接続",
                "   - プレイヤー操作、敵AI、当たり判定などの基本動作",
                "   - デバッグログで動作確認を行う",
                "   理由: UIとロジックを分離することで、動作確認がしやすく修正も容易",
                "",
                "3. 演出実装",
                "   - パーティクル、アニメーション、サウンド、エフェクト",
                "   - UI遷移アニメーション、フィードバック演出",
                "   - カメラワーク、シェイク、画面効果",
                "   理由: 演出は最後に追加しても動作に影響せず、調整も独立して行える",
                "",
                "この順序により、各段階で動作確認しながら段階的に完成度を上げられる。",
                "",
                "【C#スクリプト作成ルール】",
                "- [SerializeField] private変数には、必ずpublic読み取り専用プロパティを作成",
                "  例: [SerializeField] private int health = 100; → public int Health => health;",
                "- 作成/更新後は可能な限り変更をまとめてから unity.project.compile で一度コンパイル実行",
                "- コンパイルエラー発生時はエラー内容を確認して修正し、再コンパイル",
                "",
                "【ヒエラルキー操作ガイド】",
                "1. GameObjectの作成",
                "   - unity.gameobject.crud で operation='create' を使用",
                "   - name: オブジェクト名を指定（必須）",
                "   - parentPath: 親オブジェクトのパス（省略時はルート）",
                "   - template: テンプレートやプレハブのパスを指定可能",
                "   例: unity.gameobject.crud(operation='create', name='Player', parentPath='Game/Characters')",
                "",
                "2. 階層構造の確認",
                "   - 作業前に unity.scene.crud(operation='inspect', includeHierarchy=True) で現在のヒエラルキーを確認（1階層のみ返す）",
                "   - 深い階層は unity.gameobject.crud(operation='inspect', gameObjectPath='...') で個別に確認",
                "   - 既存オブジェクトを確認してから新規作成・移動を実行",
                "   - gameObjectPath はルートからの完全パス（例: 'Canvas/Panel/Button'）",
                "",
                "3. オブジェクトの移動・整理",
                "   - unity.gameobject.crud で operation='move' を使用",
                "   - parentPath に移動先の親オブジェクトパスを指定",
                "   例: unity.gameobject.crud(operation='move', gameObjectPath='Player', parentPath='Game/Characters')",
                "",
                "4. テンプレートの活用",
                "   - unity.gameobject.createFromTemplate でよくあるオブジェクトを簡単作成",
                "   - template: 'Cube', 'Sphere', 'Camera', 'Light-Directional', 'Empty' など",
                "   - position, rotation, scale も同時に設定可能",
                "   例: unity.gameobject.createFromTemplate(template='Cube', name='Platform', position={'x': 0, 'y': -1, 'z': 0})",
                "",
                "5. 既存オブジェクトのカスタマイズ",
                "   - unity.template.manage で既存GameObjectに複数のコンポーネントと子オブジェクトを一括追加",
                "   - operation='customize': コンポーネント配列とchildren配列を指定",
                "   - operation='convertToPrefab': カスタマイズ後にPrefabとして保存",
                "   例: unity.template.manage(operation='customize', gameObjectPath='Player', components=[...], children=[...])",
                "",
                "【コンポーネント設定ガイド】",
                "1. コンポーネントの追加",
                "   - unity.component.crud で operation='add' を使用",
                "   - componentType: 完全修飾名を指定（例: 'UnityEngine.Rigidbody'）",
                "   - propertyChanges: 初期値を設定（省略可）",
                "   例: unity.component.crud(operation='add', gameObjectPath='Player', componentType='UnityEngine.Rigidbody', propertyChanges={'mass': 2.0, 'useGravity': True})",
                "",
                "2. コンポーネントの更新",
                "   - unity.component.crud で operation='update' を使用",
                "   - propertyChanges: 変更したいプロパティのみを指定",
                "   - 複数のプロパティを一度に更新可能",
                "   - [SerializeField] private フィールドも読み書き可能（Unityのシリアライズルールに従う）",
                "   例: unity.component.crud(operation='update', gameObjectPath='Player', componentType='UnityEngine.Transform', propertyChanges={'position': {'x': 0, 'y': 1, 'z': 0}})",
                "",
                "3. Unity Object参照の設定（重要）",
                "   - Mesh, Material, Sprite などのアセット参照を設定する場合:",
                "   a) アセットパス直接指定: 'Assets/Models/Sphere.fbx'",
                "   b) GUID指定（推奨）: {'_ref': 'asset', 'guid': 'abc123...'}",
                "   c) ビルトインリソース: 'Library/unity default resources::Sphere'",
                "   例: unity.component.crud(operation='update', gameObjectPath='Cube', componentType='UnityEngine.MeshFilter', propertyChanges={'sharedMesh': 'Library/unity default resources::Sphere'})",
                "",
                "4. よくあるコンポーネントの設定例",
                "   - Transform: position, rotation, localScale",
                "   - RectTransform: anchoredPosition, sizeDelta, anchorMin, anchorMax",
                "   - Text: text, fontSize, color, alignment",
                "   - Image: sprite, color, raycastTarget",
                "   - Button: interactable, onClick",
                "   - Rigidbody: mass, drag, useGravity, constraints",
                "",
                "5. UnityEventリスナーの設定（ボタンクリック等）",
                "   - onClick等のUnityEventにリスナーを設定可能",
                "   - 単純形式: 'onClick': 'GameManager.OnButtonClick' （引数なし）",
                "   - 複雑形式: 'onClick': {'listeners': [{'targetPath': 'GameManager', 'methodName': 'OnButtonClick', 'mode': 'Void'}]}",
                "   - サポートモード: Void, Int, Float, String, Bool, Object",
                "   例: unity.component.crud(operation='update', gameObjectPath='Canvas/Button', componentType='UnityEngine.UI.Button', propertyChanges={'onClick': 'GameManager.StartGame'})",
                "",
                "6. パフォーマンス最適化（inspect操作）",
                "   - includeProperties=False: プロパティ読み込みをスキップ（存在確認のみ、10倍高速）",
                "   - propertyFilter=[...]: 特定プロパティのみ取得（例: ['position', 'rotation']）",
                "   - 例（高速）: unity.component.crud(operation='inspect', gameObjectPath='Player', componentType='UnityEngine.Transform', includeProperties=False)",
                "   - 例（特定）: unity.component.crud(operation='inspect', gameObjectPath='Player', componentType='UnityEngine.Transform', propertyFilter=['position'])",
                "",
                "7. バッチ操作（複数GameObject処理）",
                "   - operation='addMultiple', 'removeMultiple', 'updateMultiple', 'inspectMultiple'",
                "   - maxResults: 処理上限（デフォルト1000、タイムアウト防止）",
                "   - stopOnError=False: エラー発生時も継続処理",
                "   例: unity.component.crud(operation='addMultiple', pattern='Enemy*', componentType='UnityEngine.Rigidbody', maxResults=100, stopOnError=False)",
                "",
                "8. GameObject識別方法",
                "   - gameObjectPath: 階層パス（例: 'Canvas/Panel/Button'）",
                "   - gameObjectGlobalObjectId: GlobalObjectId文字列（シーン再読み込み後も安定、階層移動に強い）",
                "   - 優先順位: GlobalObjectId > gameObjectPath",
                "",
                "【UI要素作成の典型パターン】",
                "1. Canvas配下のUI作成",
                "   a) unity.scene.crud(operation='inspect', includeHierarchy=True) でCanvasの存在を確認（1階層のみ返す）",
                "   b) unity.ugui.createFromTemplate でUI要素を作成",
                "      template: 'Button', 'Text', 'Image', 'Panel', 'InputField' など",
                "   c) unity.ugui.manage で RectTransform を調整",
                "   d) unity.component.crud でテキストや色などのプロパティを設定",
                "",
                "2. レイアウトグループの設定",
                "   - unity.ugui.layoutManage を使用",
                "   - HorizontalLayoutGroup, VerticalLayoutGroup, GridLayoutGroup を追加・設定",
                "   例: unity.ugui.layoutManage(operation='add', gameObjectPath='Canvas/Panel', layoutType='VerticalLayoutGroup', spacing=10)",
                "",
                "3. 階層メニューシステムの作成",
                "   - unity.menu.hierarchyCreate で完全なメニューシステムを一括生成",
                "   - ネストされたサブメニュー、ボタン、レイアウト、State patternナビゲーションを自動作成",
                "   - generateStateMachine=True で MenuStateMachine スクリプトも生成",
                "   例: unity.menu.hierarchyCreate(menuName='MainMenu', menuStructure={'Play': 'Start Game', 'Settings': {...}, 'Quit': 'Exit'}, generateStateMachine=True, stateMachineScriptPath='Assets/Scripts/MenuManager.cs')",
                "",
                "【3Dオブジェクト配置の典型パターン】",
                "1. プリミティブ配置",
                "   a) unity.gameobject.createFromTemplate で基本形状作成",
                "   b) unity.component.crud で Transform を調整",
                "   c) 必要に応じて Rigidbody, Collider を追加",
                "",
                "2. マテリアル・メッシュ設定",
                "   a) unity.asset.crud でマテリアルアセットを確認",
                "   b) unity.component.crud で MeshRenderer の material を設定",
                "   c) unity.component.crud で MeshFilter の sharedMesh を設定",
                "",
                "【作業の流れの推奨手順】",
                "1. 作業前: unity.scene.crud(operation='inspect', includeHierarchy=True) で現状確認（1階層のみ）",
                "2. 深い階層: unity.gameobject.crud(operation='inspect', gameObjectPath='Parent/Child') で個別確認",
                "3. 作成: unity.gameobject.crud または createFromTemplate でオブジェクト作成",
                "4. 配置: unity.component.crud で Transform を設定",
                "5. コンポーネント追加: unity.component.crud で必要なコンポーネントを追加",
                "6. プロパティ設定: unity.component.crud で各コンポーネントのプロパティを設定",
                "7. 確認: unity.gameobject.crud の operation='inspect' で設定を確認",
                "",
                "【C#スクリプト生成】",
                "1. テンプレート生成（推奨）",
                "   - unity.script.template.generate でMonoBehaviour/ScriptableObjectのテンプレート生成",
                "   - 標準ライフサイクルメソッド付き、namespace対応",
                "   - templateType: 'MonoBehaviour' または 'ScriptableObject'",
                "   例: unity.script.template.generate(templateType='MonoBehaviour', className='PlayerController', scriptPath='Assets/Scripts/PlayerController.cs', namespace='MyGame.Player')",
                "",
                "2. スクリプト編集",
                "   - unity.asset.crud(operation='update', assetPath='...', content='...') でスクリプト内容を更新",
                "   - unity.await.compilation で自動コンパイル完了を待機",
                "",
                "【デザインパターン生成】",
                "- unity.designPattern.generate で実装済みデザインパターンを即座に生成",
                "- パターン: singleton, objectpool, statemachine, observer, command, factory, servicelocator",
                "- 完全なコメント付き本番コード、Unity最適化済み",
                "例（Singleton）: unity.designPattern.generate(patternType='singleton', className='GameManager', scriptPath='Assets/Scripts/GameManager.cs', options={'persistent': True, 'monoBehaviour': True})",
                "例（ObjectPool）: unity.designPattern.generate(patternType='objectpool', className='BulletPool', scriptPath='Assets/Scripts/BulletPool.cs', options={'pooledType': 'GameObject', 'defaultCapacity': '50'})",
            ]
        ),
    )

    register_resources(server)
    register_tools(server)

    return server

