from __future__ import annotations

from mcp.server import Server

from resources.register_resources import register_resources
from tools.register_tools import register_tools
from version import SERVER_NAME, SERVER_VERSION


def create_mcp_server() -> Server:
    server = Server(
        SERVER_NAME,
        version=SERVER_VERSION,
        instructions="\n".join(
            [
                "Unityプロジェクトと連携する拡張版MCPサーバーです。",
                "resourcesからプロジェクト構造、シーン、ログ、アセットを参照し、toolsでUnityEditorを操作します。",
                "",
                "【ツール使用の原則】",
                "- UnityEditor操作は必ずMCPツール（unity.asset.crud、unity.gameobject.crud、unity.component.crud等）を使用する事",
                "- パラメータ取得やファイル読み書きも直接行わず、MCPツールを使用する事",
                "- ツール実行前に対象のオブジェクト/アセットのパスを確認する事",
                "- 接続タイムアウト時や切断時はコンパイルエラーを確認する事",
                "",
                "【開発時の注意点】",
                "- 必要最小限の変更に留め、既存アセットを活用する事",
                "- ユーザーが明示的に要求した場合のみエディタ操作を実行する事",
                "",
                "【開発作業の優先順位】",
                "1. C#スクリプトの作成（プロジェクトの基礎）",
                "2. GameObjectとコンポーネントの設定",
                "3. シーン構成とプレハブの作成",
                "",
                "【ゲームプロジェクト実装の推奨順序】",
                "ゲーム開発では以下の順序で実装することを強く推奨:",
                "1. UI実装",
                "   - まずゲームに必要なUIを全て作成・配置",
                "   - ボタン、テキスト、パネル、HUDなどの基本UI要素",
                "   - レイアウトとアンカー設定を完了させる",
                "   - この段階ではイベントハンドラは空のままでOK",
                "   理由: UIは後から追加すると位置調整やレイアウト崩れが発生しやすい",
                "",
                "2. ロジック実装",
                "   - ゲームの核となるロジック（ゲームルール、状態管理、スコア計算等）",
                "   - UIのイベントハンドラとロジックを接続",
                "   - プレイヤー操作、敵AI、当たり判定などの基本動作",
                "   - デバッグログで動作確認を行う",
                "   理由: UIとロジックを分離することで、動作確認がしやすく修正も容易",
                "",
                "3. 演出実装",
                "   - パーティクル、アニメーション、サウンド、エフェクト",
                "   - UI遷移アニメーション、フィードバック演出",
                "   - カメラワーク、シェイク、画面効果",
                "   理由: 演出は最後に追加しても動作に影響せず、調整も独立して行える",
                "",
                "この順序により、各段階で動作確認しながら段階的に完成度を上げられる。",
                "",
                "【C#スクリプト作成ルール】",
                "- [SerializeField] private変数には、必ずpublic読み取り専用プロパティを作成",
                "  例: [SerializeField] private int health = 100; → public int Health => health;",
                "- 作成/更新後は可能な限り変更をまとめてから unity.project.compile で一度コンパイル実行",
                "- コンパイルエラー発生時はエラー内容を確認して修正し、再コンパイル",
                "",
                "【ヒエラルキー操作ガイド】",
                "1. GameObjectの作成",
                "   - unity.gameobject.crud で operation='create' を使用",
                "   - name: オブジェクト名を指定（必須）",
                "   - parentPath: 親オブジェクトのパス（省略時はルート）",
                "   - template: テンプレートやプレハブのパスを指定可能",
                "   例: unity.gameobject.crud(operation='create', name='Player', parentPath='Game/Characters')",
                "",
                "2. 階層構造の確認",
                "   - 作業前に unity.context.inspect で現在のヒエラルキーを確認",
                "   - 既存オブジェクトを確認してから新規作成・移動を実行",
                "   - gameObjectPath はルートからの完全パス（例: 'Canvas/Panel/Button'）",
                "",
                "3. オブジェクトの移動・整理",
                "   - unity.gameobject.crud で operation='move' を使用",
                "   - parentPath に移動先の親オブジェクトパスを指定",
                "   例: unity.gameobject.crud(operation='move', gameObjectPath='Player', parentPath='Game/Characters')",
                "",
                "4. テンプレートの活用",
                "   - unity.gameobject.createFromTemplate でよくあるオブジェクトを簡単作成",
                "   - template: 'Cube', 'Sphere', 'Camera', 'Light-Directional', 'Empty' など",
                "   - position, rotation, scale も同時に設定可能",
                "   例: unity.gameobject.createFromTemplate(template='Cube', name='Platform', position={'x': 0, 'y': -1, 'z': 0})",
                "",
                "【コンポーネント設定ガイド】",
                "1. コンポーネントの追加",
                "   - unity.component.crud で operation='add' を使用",
                "   - componentType: 完全修飾名を指定（例: 'UnityEngine.Rigidbody'）",
                "   - propertyChanges: 初期値を設定（省略可）",
                "   例: unity.component.crud(operation='add', gameObjectPath='Player', componentType='UnityEngine.Rigidbody', propertyChanges={'mass': 2.0, 'useGravity': True})",
                "",
                "2. コンポーネントの更新",
                "   - unity.component.crud で operation='update' を使用",
                "   - propertyChanges: 変更したいプロパティのみを指定",
                "   - 複数のプロパティを一度に更新可能",
                "   例: unity.component.crud(operation='update', gameObjectPath='Player', componentType='UnityEngine.Transform', propertyChanges={'position': {'x': 0, 'y': 1, 'z': 0}})",
                "",
                "3. Unity Object参照の設定（重要）",
                "   - Mesh, Material, Sprite などのアセット参照を設定する場合:",
                "   a) アセットパス直接指定: 'Assets/Models/Sphere.fbx'",
                "   b) GUID指定（推奨）: {'_ref': 'asset', 'guid': 'abc123...'}",
                "   c) ビルトインリソース: 'Library/unity default resources::Sphere'",
                "   例: unity.component.crud(operation='update', gameObjectPath='Cube', componentType='UnityEngine.MeshFilter', propertyChanges={'sharedMesh': 'Library/unity default resources::Sphere'})",
                "",
                "4. よくあるコンポーネントの設定例",
                "   - Transform: position, rotation, localScale",
                "   - RectTransform: anchoredPosition, sizeDelta, anchorMin, anchorMax",
                "   - Text: text, fontSize, color, alignment",
                "   - Image: sprite, color, raycastTarget",
                "   - Button: interactable, onClick (イベントはスクリプトで設定)",
                "   - Rigidbody: mass, drag, useGravity, constraints",
                "",
                "【UI要素作成の典型パターン】",
                "1. Canvas配下のUI作成",
                "   a) unity.context.inspect でCanvasの存在を確認",
                "   b) unity.ugui.createFromTemplate でUI要素を作成",
                "      template: 'Button', 'Text', 'Image', 'Panel', 'InputField' など",
                "   c) unity.ugui.manage で RectTransform を調整",
                "   d) unity.component.crud でテキストや色などのプロパティを設定",
                "",
                "2. レイアウトグループの設定",
                "   - unity.ugui.layoutManage を使用",
                "   - HorizontalLayoutGroup, VerticalLayoutGroup, GridLayoutGroup を追加・設定",
                "   例: unity.ugui.layoutManage(operation='add', gameObjectPath='Canvas/Panel', layoutType='VerticalLayoutGroup', spacing=10)",
                "",
                "【3Dオブジェクト配置の典型パターン】",
                "1. プリミティブ配置",
                "   a) unity.gameobject.createFromTemplate で基本形状作成",
                "   b) unity.component.crud で Transform を調整",
                "   c) 必要に応じて Rigidbody, Collider を追加",
                "",
                "2. マテリアル・メッシュ設定",
                "   a) unity.asset.crud でマテリアルアセットを確認",
                "   b) unity.component.crud で MeshRenderer の material を設定",
                "   c) unity.component.crud で MeshFilter の sharedMesh を設定",
                "",
                "【作業の流れの推奨手順】",
                "1. 作業前: unity.context.inspect で現状確認",
                "2. 作成: unity.gameobject.crud または createFromTemplate でオブジェクト作成",
                "3. 配置: unity.component.crud で Transform を設定",
                "4. コンポーネント追加: unity.component.crud で必要なコンポーネントを追加",
                "5. プロパティ設定: unity.component.crud で各コンポーネントのプロパティを設定",
                "6. 確認: unity.gameobject.crud の operation='inspect' で設定を確認",
            ]
        ),
    )

    register_resources(server)
    register_tools(server)

    return server

