from __future__ import annotations

from mcp.server import Server

from resources.register_resources import register_resources
from tools.register_tools import register_tools
from version import SERVER_NAME, SERVER_VERSION


def create_mcp_server() -> Server:
    server = Server(
        SERVER_NAME,
        version=SERVER_VERSION,
        instructions="\n".join(
            [
                "# Unity MCP Server - Quick Reference",
                "Unityプロジェクトと連携するMCPサーバー。resourcesでプロジェクト構造参照、toolsでUnityEditor操作。",
                "",
                "## 🔴 Critical Rules (必ず守る)",
                "1. .metaファイルは絶対に編集しない（Unity自動管理、手動編集は参照破壊）",
                "2. 全Unity操作にMCPツール（unity_*）を使用",
                "3. 変更前に operation='inspect' で対象を確認",
                "4. テンプレート機能を優先活用（手動作成より10倍高速）",
                "",
                "## 基本ワークフロー",
                "1. 確認: unity_scene_crud(operation='inspect', includeHierarchy=True) # 1階層のみ返す",
                "2. 操作: 対応ツールで変更実施",
                "3. 検証: operation='inspect' で結果確認",
                "",
                "## Core Operations",
                "",
                "### Scene & GameObject",
                "- 作成: unity_gameobject_crud(operation='create', name='...', parentPath='...')",
                "- テンプレート: unity_gameobject_createFromTemplate(template='Cube'|'Sphere'|'Camera'|'Light-Directional'|'Empty'|'Player')",
                "- 複数検索: unity_gameobject_crud(operation='findMultiple', pattern='Enemy*', maxResults=100)",
                "- 移動: unity_gameobject_crud(operation='move', gameObjectPath='...', parentPath='...')",
                "- 複雑構造: unity_template_manage(operation='customize', gameObjectPath='...', components=[...], children=[...])",
                "",
                "### Component",
                "- 追加: unity_component_crud(operation='add', gameObjectPath='...', componentType='UnityEngine.Rigidbody', propertyChanges={...})",
                "- 更新: unity_component_crud(operation='update', gameObjectPath='...', componentType='...', propertyChanges={...})",
                "- アセット参照: propertyChanges={'sharedMesh': 'Library/unity default resources::Sphere'} または {'_ref': 'asset', 'guid': '...'}",
                "- UnityEvent: propertyChanges={'onClick': 'GameManager.OnButtonClick'} または {'onClick': {'listeners': [...]}}",
                "- バッチ追加: unity_component_crud(operation='addMultiple', pattern='Enemy*', componentType='...', stopOnError=False, maxResults=100)",
                "- バッチ更新: operation='updateMultiple'",
                "",
                "### UI (ゲーム開発の最初に実装推奨)",
                "理由: 後からの追加は位置調整とレイアウト崩れが発生しやすい",
                "- 作成: unity_ugui_createFromTemplate(template='Button'|'Text'|'Image'|'Panel'|'InputField'|'Slider', name='...', parentPath='Canvas/...', width=..., height=..., text='...')",
                "- アンカー: unity_ugui_manage(operation='setAnchorPreset', gameObjectPath='...', preset='middle-center'|'top-left'|'stretch-all', preservePosition=True)",
                "- RectTransform更新: unity_ugui_manage(operation='updateRect', gameObjectPath='...', anchoredPosition={'x': 0, 'y': 0}, sizeDelta={'x': 200, 'y': 60})",
                "- レイアウト: unity_ugui_layoutManage(operation='add', gameObjectPath='...', layoutType='VerticalLayoutGroup'|'HorizontalLayoutGroup'|'GridLayoutGroup', spacing=10, padding={...})",
                "- メニュー階層: unity_menu_hierarchyCreate(menuName='...', menuStructure={...}, generateStateMachine=True, stateMachineScriptPath='...')",
                "",
                "### Asset & Script",
                "- テキストファイル作成: unity_asset_crud(operation='create', assetPath='Assets/Data/config.json', content='...')",
                "- 更新: unity_asset_crud(operation='update', assetPath='...', content='...')",
                "- インポーター設定: unity_asset_crud(operation='updateImporter', assetPath='...', propertyChanges={...})",
                "- スクリプト生成: unity_script_template_generate(templateType='MonoBehaviour'|'ScriptableObject', className='...', scriptPath='Assets/Scripts/....cs', namespace='...')",
                "- デザインパターン: unity_designPattern_generate(patternType='singleton'|'objectpool'|'statemachine'|'observer'|'command'|'factory', className='...', scriptPath='...', options={...})",
                "- コンパイル待機: unity_await_compilation(timeoutSeconds=60) # 変更まとめてから実行",
                "",
                "### ScriptableObject",
                "- 作成: unity_scriptableObject_crud(operation='create', typeName='MyGame.GameConfig', assetPath='Assets/Data/....asset', properties={...})",
                "- 検査: unity_scriptableObject_crud(operation='inspect', assetPath='...', includeProperties=True, propertyFilter=['version', 'maxPlayers'])",
                "- 更新: unity_scriptableObject_crud(operation='update', assetPath='...', properties={...})",
                "- 型検索: unity_scriptableObject_crud(operation='findByType', typeName='...', searchPath='Assets/Data', maxResults=100)",
                "",
                "### Prefab",
                "- 作成: unity_prefab_crud(operation='create', gameObjectPath='...', prefabPath='Assets/Prefabs/....prefab', includeChildren=True)",
                "- インスタンス化: unity_prefab_crud(operation='instantiate', prefabPath='...', parentPath='...')",
                "- オーバーライド適用: unity_prefab_crud(operation='applyOverrides', gameObjectPath='...')",
                "- オーバーライド破棄: unity_prefab_crud(operation='revertOverrides', gameObjectPath='...')",
                "",
                "### Vector Sprite (プロトタイプ用)",
                "外部アセット不要で即座に生成。ゲームジャム、プロトタイピング、プレースホルダーに最適。",
                "- プリミティブ: unity_vectorSprite_convert(operation='primitiveToSprite', primitiveType='circle'|'square'|'triangle'|'polygon', color={'r':1,'g':0,'b':0,'a':1}, outputPath='Assets/Sprites/....png', width=256, height=256)",
                "- 単色: unity_vectorSprite_convert(operation='createColorSprite', width=64, height=64, color={...}, outputPath='...')",
                "- SVG変換: unity_vectorSprite_convert(operation='svgToSprite', svgPath='...', outputPath='...', width=512, height=512)",
                "- テクスチャ→スプライト: unity_vectorSprite_convert(operation='textureToSprite', texturePath='...', pixelsPerUnit=100, filterMode='point'|'bilinear')",
                "",
                "## ⚡ Performance Optimization (重要)",
                "",
                "### 高速化テクニック:",
                "1. includeProperties=False: コンポーネント存在確認のみ（10倍高速）",
                "   unity_component_crud(operation='inspect', gameObjectPath='...', componentType='...', includeProperties=False)",
                "2. propertyFilter: 必要なプロパティのみ取得",
                "   unity_component_crud(operation='inspect', ..., propertyFilter=['position', 'rotation'])",
                "3. maxResults: 大量操作時のタイムアウト防止",
                "   unity_gameobject_crud(operation='findMultiple', pattern='*', maxResults=100)",
                "4. stopOnError=False: バッチ処理でエラー時も続行",
                "   unity_component_crud(operation='addMultiple', pattern='Enemy*', ..., stopOnError=False)",
                "",
                "### バッチ操作（推奨）:",
                "*Multiple操作を使用: addMultiple, updateMultiple, deleteMultiple, inspectMultiple",
                "❌ 避ける: ループ内で個別ツール呼び出し",
                "✅ 推奨: unity_component_crud(operation='addMultiple', pattern='Enemy*', componentType='UnityEngine.Rigidbody', maxResults=100)",
                "",
                "## 🎮 Game Development Best Practices",
                "",
                "### 推奨実装順序:",
                "1. UI実装（最初）",
                "   - 理由: 後からの追加は位置調整とレイアウト崩れが発生しやすい",
                "   - 全UI要素を作成・配置、レイアウトとアンカー設定完了",
                "   - イベントハンドラは空でOK",
                "",
                "2. ロジック実装",
                "   - ゲームルール、状態管理、スコア計算",
                "   - UIイベントとロジック接続",
                "   - デバッグログで動作確認",
                "",
                "3. 演出実装（最後）",
                "   - パーティクル、アニメーション、サウンド",
                "   - UI遷移、フィードバック演出",
                "   - 理由: 動作に影響せず、独立して調整可能",
                "",
                "### C#スクリプトルール:",
                "- [SerializeField] private変数 → public読み取り専用プロパティ必須",
                "  例: [SerializeField] private int health; → public int Health => health;",
                "- コンパイル: 変更まとめてから unity_await_compilation で一度実行",
                "",
                "## 🔧 Troubleshooting",
                "",
                "### 接続エラー",
                "1. unity_ping で接続確認",
                "2. Unity Editorで Tools > MCP Assistant が起動しているか確認",
                "",
                "### コンパイルエラー",
                "1. unity_await_compilation(timeoutSeconds=60) で詳細取得",
                "2. 戻り値の consoleLogs.errors を確認",
                "3. エラー修正後、再度 unity_await_compilation",
                "",
                "### タイムアウト",
                "1. maxResults を減らす（デフォルト1000）",
                "2. includeProperties=False で高速化",
                "3. stopOnError=False でバッチ操作続行",
                "",
                "### 接続切断・タイムアウト",
                "1. unity_await_compilation でコンパイルエラー確認",
                "2. Unity Editorのコンソールログをチェック",
                "3. 長時間操作は maxResults で分割実行",
                "",
                "## Additional Tools",
                "",
                "### Scene Setup",
                "- クイックセットアップ: unity_scene_quickSetup(setupType='3D'|'2D'|'UI'|'VR'|'Empty', cameraPosition={...}, lightIntensity=1.0)",
                "",
                "### Tags & Layers",
                "- タグ追加: unity_tagLayer_manage(operation='addTag', tag='...')",
                "- タグ設定: unity_tagLayer_manage(operation='setTag', gameObjectPath='...', tag='...')",
                "- レイヤー追加: unity_tagLayer_manage(operation='addLayer', layer='...')",
                "- レイヤー再帰設定: unity_tagLayer_manage(operation='setLayerRecursive', gameObjectPath='...', layer='...')",
                "",
                "### Project Settings",
                "- 読み取り: unity_projectSettings_crud(operation='read', category='player'|'quality'|'time'|'physics'|'audio'|'editor', property='...')",
                "- 書き込み: unity_projectSettings_crud(operation='write', category='...', property='...', value=...)",
                "",
                "### Constants",
                "- Enum→値: unity_constant_convert(operation='enumToValue', enumType='UnityEngine.KeyCode', enumValue='Space')",
                "- 値→Enum: unity_constant_convert(operation='valueToEnum', enumType='...', numericValue=32)",
                "- 色→RGBA: unity_constant_convert(operation='colorToRGBA', colorName='red')",
                "",
                "### Build Settings",
                "- 一覧: unity_scene_crud(operation='listBuildSettings')",
                "- 追加: unity_scene_crud(operation='addToBuildSettings', scenePath='...', index=1, enabled=True)",
                "- 削除: unity_scene_crud(operation='removeFromBuildSettings', index=0)",
                "- 並べ替え: unity_scene_crud(operation='reorderBuildSettings', fromIndex=0, toIndex=2)",
                "",
                "## よくある使用パターン",
                "",
                "### GameObject識別方法",
                "- gameObjectPath: 階層パス（例: 'Canvas/Panel/Button'）",
                "- gameObjectGlobalObjectId: GlobalObjectId文字列（シーン再読み込み後も安定、階層移動に強い）",
                "- 優先順位: GlobalObjectId > gameObjectPath",
                "",
                "### よくあるコンポーネントプロパティ",
                "- Transform: position, rotation, localScale",
                "- RectTransform: anchoredPosition, sizeDelta, anchorMin, anchorMax, pivot, offsetMin, offsetMax",
                "- Text: text, fontSize, color, alignment",
                "- Image: sprite, color, raycastTarget",
                "- Button: interactable, onClick",
                "- Rigidbody: mass, drag, useGravity, constraints",
                "- Camera: fieldOfView, clearFlags, backgroundColor",
                "- Light: intensity, color, type, range",
                "",
                "### 3Dオブジェクト配置パターン",
                "1. unity_gameobject_createFromTemplate(template='Cube'|'Sphere'|'Plane', position={...}, rotation={...}, scale={...})",
                "2. unity_component_crud(operation='add', componentType='UnityEngine.Rigidbody', propertyChanges={...})",
                "3. unity_asset_crud(operation='inspect', assetPath='Assets/Materials/...') でマテリアル確認",
                "4. unity_component_crud(operation='update', componentType='UnityEngine.MeshRenderer', propertyChanges={'material': 'Assets/Materials/...'})",
                "",
                "ツール名は全て unity_* 形式（アンダースコア区切り）。例: unity_gameobject_crud, unity_component_crud",
            ]
        ),
    )

    register_resources(server)
    register_tools(server)

    return server

